<?php

namespace Rofil\Repo\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
	public function search($keyword="")
	{
		$qb = $this->createQueryBuilder("p")
			->where("p.published=1")
			->andWhere("p.title like :title or p.body like :body")
			->setParameter("title", "%$keyword%")
			->setParameter("body", "%$keyword%")
			->orderBy("p.createdAt", "DESC")
			->getQuery()->getResult()
		;
		return $qb;
	}

	public function all()
	{
		$qb = $this->createQueryBuilder("p")
			// ->setFirstResult(0)
			// ->setMaxResults($limit)
			->orderBy("p.createdAt", "DESC")
			->getQuery()->getResult()
		;
		return $qb;
	}

	public function get(array $options)
	{
		$qb = $this->createQueryBuilder("p")
			->orderBy("p.createdAt", "DESC")
		;
		if(array_key_exists("limit", $options)){
			$qb->setFirstResult(0)->setMaxResults($options['limit']);
		}
		if(array_key_exists("except", $options)){
			$qb->where("p.id <> :except")->setParameter("except", $options['except']);
		}
		return $qb->getQuery()->getResult();
	}
}
